import { APP_VERSION, TEMPLATE_VERSION, DRAFT_FORMAT_VERSION, sections, emptyBrief } from "./sections.js";

const DB_NAME = "legal-brief-builder";
const DB_VERSION = 1;
const STORE_NAME = "drafts";
const state = { brief: null, exampleIndexes: {}, saveTimer: null, revisionTimer: null };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];

function openDatabase() {
  return new Promise((resolve, reject) => {
    if (!window.indexedDB) return reject(new Error("IndexedDB is unavailable in this browser."));
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => request.result.createObjectStore(STORE_NAME, { keyPath: "id" });
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error || new Error("Could not open local storage."));
  });
}
async function databaseAction(mode, action) {
  const db = await openDatabase();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction(STORE_NAME, mode);
    const request = action(transaction.objectStore(STORE_NAME));
    request.onsuccess = () => { db.close(); resolve(request.result); };
    request.onerror = () => { db.close(); reject(request.error); };
  });
}
const saveDraft = brief => databaseAction("readwrite", store => store.put(structuredClone(brief)));
const getDrafts = () => databaseAction("readonly", store => store.getAll());
const removeDraft = id => databaseAction("readwrite", store => store.delete(id));

function formatDate(iso) { return iso ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(iso)) : "Unknown"; }
function notify(message, error = false) { const toast = document.createElement("div"); toast.className = `toast${error ? " error" : ""}`; toast.textContent = message; $("#toast-region").append(toast); setTimeout(() => toast.remove(), 4000); }
function setStatus(message, saving = false) { const status = $("#save-status"); status.textContent = message; status.classList.toggle("saving", saving); }
function escapeText(value) { return String(value ?? ""); }
function scheduleSave() {
  setStatus("Saving…", true); clearTimeout(state.saveTimer);
  state.saveTimer = setTimeout(async () => {
    state.brief.modifiedAt = new Date().toISOString(); state.brief.provenance.lastModifiedAt = state.brief.modifiedAt;
    try { await saveDraft(state.brief); setStatus(`Saved ${formatDate(state.brief.modifiedAt)}`); } catch (error) { setStatus("Could not save locally", true); notify("Your draft could not be saved to this browser. Export a .brief backup now.", true); }
  }, 700);
}
function substantiveData() { return { title: state.brief.title, caseInformation: state.brief.caseInformation, sections: state.brief.sections }; }
async function createRevision(reason = "edit") {
  const encoded = new TextEncoder().encode(JSON.stringify(substantiveData()));
  const digest = await crypto.subtle.digest("SHA-256", encoded);
  const contentHash = [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join("");
  const text = JSON.stringify(substantiveData()); const last = state.brief.provenance.revisions.at(-1);
  if (last?.contentHash === contentHash) return;
  state.brief.provenance.revisions.push({ revisionNumber: (last?.revisionNumber || 0) + 1, timestamp: new Date().toISOString(), contentHash, wordCount: text.trim().split(/\s+/).filter(Boolean).length, characterCount: text.length, reason });
  if (state.brief.provenance.revisions.length > 100) state.brief.provenance.revisions.shift();
}
function handleEdit() { clearTimeout(state.revisionTimer); scheduleSave(); state.revisionTimer = setTimeout(() => createRevision(), 1600); }

function renderNavigation() { $("#section-count").textContent = sections.length; $("#section-nav").replaceChildren(...sections.map((section, index) => { const button = document.createElement("button"); button.className = "nav-link"; button.textContent = `${String(index + 1).padStart(2, "0")}  ${section.title.replace("Case Name, Court, Citation, Date", "Case information")}`; button.dataset.target = section.id; button.addEventListener("click", () => document.getElementById(section.id).scrollIntoView({ behavior: "smooth" })); return button; })); }
function makeTextarea(section) { const textarea = document.createElement("textarea"); textarea.className = "editor-textarea"; textarea.id = `field-${section.id}`; textarea.placeholder = "Start writing here…"; textarea.spellcheck = true; textarea.value = state.brief.sections[section.id] || ""; textarea.addEventListener("input", event => { state.brief.sections[section.id] = event.target.value; textarea.style.height = "auto"; textarea.style.height = `${textarea.scrollHeight}px`; handleEdit(); }); return textarea; }
function renderEditor() {
  const editor = $("#editor"); editor.replaceChildren();
  sections.forEach((section, index) => {
    const wrapper = document.createElement("article"); wrapper.className = "brief-section"; wrapper.id = section.id;
    const number = document.createElement("div"); number.className = "section-number"; number.textContent = String(index + 1).padStart(2, "0");
    const main = document.createElement("div"); main.className = "section-main"; const heading = document.createElement("h2"); heading.textContent = section.title; main.append(heading);
    if (section.type === "metadata") { const grid = document.createElement("div"); grid.className = "field-grid"; section.fields.forEach(field => { const label = document.createElement("label"); label.className = "field-label"; label.textContent = field.label; const input = document.createElement("input"); input.className = "editor-input"; input.placeholder = field.placeholder; input.value = state.brief.caseInformation[field.id] || ""; input.addEventListener("input", event => { state.brief.caseInformation[field.id] = event.target.value; if (field.id === "caseName" && state.brief.title === "Untitled brief") { state.brief.title = event.target.value || "Untitled brief"; $("#brief-title").value = state.brief.title; } handleEdit(); }); const hint = document.createElement("small"); hint.className = "field-hint"; hint.textContent = `Example: ${field.example}`; label.append(input, hint); grid.append(label); }); main.append(grid); } else main.append(makeTextarea(section));
    const controls = document.createElement("div"); controls.className = "section-help"; const help = document.createElement("button"); help.className = "help-button"; help.textContent = "?"; help.title = "Show instructions"; help.setAttribute("aria-label", `Instructions for ${section.title}`); help.addEventListener("click", () => showHelp(section)); controls.append(help);
    if (section.examples?.length) { const examples = document.createElement("button"); examples.className = "examples-button"; examples.innerHTML = `<span aria-hidden="true">↗</span> See an example`; examples.addEventListener("click", () => showExample(section)); controls.append(examples); } else { const text = document.createElement("span"); text.className = "control-label"; text.textContent = "Identify the case"; controls.append(text); }
    wrapper.append(number, main, controls); editor.append(wrapper);
  });
  $$(".editor-textarea").forEach(textarea => { textarea.style.height = "auto"; textarea.style.height = `${textarea.scrollHeight}px`; });
}
function showHelp(section) { $("#help-title").textContent = section.title; const content = $("#help-content"); content.replaceChildren(); const purpose = document.createElement("p"); purpose.textContent = section.purpose; content.append(purpose); const list = document.createElement("ul"); section.instructions.forEach(item => { const li = document.createElement("li"); li.textContent = item; list.append(li); }); content.append(list); $("#help-dialog").showModal(); }
function showExample(section) { const index = state.exampleIndexes[section.id] || 0; const example = section.examples[index]; $("#example-position").textContent = `${index + 1} of ${section.examples.length}`; $("#example-title").textContent = example.title; $("#example-source").textContent = example.source; $("#example-content").textContent = example.text; $("#example-dialog").dataset.sectionId = section.id; $("#example-dialog").showModal(); }
function rotateExample(direction) { const dialog = $("#example-dialog"); const section = sections.find(item => item.id === dialog.dataset.sectionId); const currentIndex = state.exampleIndexes[section.id] || 0; state.exampleIndexes[section.id] = (currentIndex + direction + section.examples.length) % section.examples.length; showExample(section); }

function updateHeader() { $("#brief-title").value = state.brief.title; $("#brief-id-label").textContent = `· ${state.brief.provenance.documentId.slice(0, 16)}`; $("#footer-version").textContent = `v${APP_VERSION}`; }
async function loadBrief(brief) { state.brief = brief; renderEditor(); updateHeader(); setStatus(`Saved ${formatDate(brief.modifiedAt)}`); window.scrollTo(0, 0); }
async function newBrief() { const brief = emptyBrief(); await loadBrief(brief); await saveDraft(brief); $("#drafts-dialog").close(); notify("New brief created"); }
function duplicateBrief(brief) { const copy = structuredClone(brief); const now = new Date().toISOString(); copy.id = `LBB-${crypto.randomUUID ? crypto.randomUUID() : Date.now()}`; copy.title = `${brief.title} copy`; copy.createdAt = now; copy.modifiedAt = now; copy.provenance = { ...copy.provenance, documentId: copy.id, createdAt: now, lastModifiedAt: now, revisions: [] }; return copy; }
async function showDrafts() { const list = $("#draft-list"); list.replaceChildren(); let drafts; try { drafts = (await getDrafts()).sort((a, b) => new Date(b.modifiedAt) - new Date(a.modifiedAt)); } catch { drafts = []; notify("Local draft storage is unavailable.", true); } if (!drafts.length) { const empty = document.createElement("p"); empty.className = "empty-state"; empty.textContent = "No saved drafts yet."; list.append(empty); } drafts.forEach(brief => { const item = document.createElement("div"); item.className = "draft-item"; const open = document.createElement("button"); open.className = "draft-open"; const name = document.createElement("strong"); name.textContent = brief.title || "Untitled brief"; const details = document.createElement("small"); details.textContent = `${brief.caseInformation?.caseName || "No case name"} · ${formatDate(brief.modifiedAt)}`; open.append(name, details); open.addEventListener("click", async () => { await loadBrief(brief); $("#drafts-dialog").close(); }); const actions = document.createElement("div"); actions.className = "draft-actions"; const duplicate = document.createElement("button"); duplicate.className = "small-action"; duplicate.textContent = "Duplicate"; duplicate.addEventListener("click", async () => { const copy = duplicateBrief(brief); await saveDraft(copy); showDrafts(); notify("Draft duplicated with a new document ID"); }); const remove = document.createElement("button"); remove.className = "small-action"; remove.textContent = "Delete"; remove.addEventListener("click", async () => { if (confirm(`Delete “${brief.title || "Untitled brief"}”?`)) { await removeDraft(brief.id); if (state.brief.id === brief.id) await newBrief(); showDrafts(); notify("Draft deleted"); } }); actions.append(duplicate, remove); item.append(open, actions); list.append(item); }); $("#drafts-dialog").showModal(); }

function download(blob, filename) { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
async function exportDraft() { await createRevision("export"); await saveDraft(state.brief); const payload = { format: "legal-brief-builder", formatVersion: DRAFT_FORMAT_VERSION, applicationVersion: APP_VERSION, brief: structuredClone(state.brief), provenance: structuredClone(state.brief.provenance) }; const filename = `${(state.brief.caseInformation.caseName || state.brief.title || "brief").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "") || "brief"}.brief`; download(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }), filename); notify("Draft exported"); }
function briefParagraphs() { return sections.flatMap(section => { if (section.type === "metadata") return []; const value = state.brief.sections[section.id]?.trim(); return value ? [{ title: section.title, text: value }] : []; }); }
async function exportPdf() { if (!window.jspdf?.jsPDF) throw new Error("PDF library is unavailable. Check your connection and reload."); const { jsPDF } = window.jspdf; const pdf = new jsPDF(); const margin = 20; let y = 24; pdf.setProperties({ title: state.brief.title, subject: "Legal case brief", author: "Legal Brief Builder", creator: "Legal Brief Builder", keywords: "legal-brief-builder" }); pdf.setFont("times", "bold"); pdf.setFontSize(18); pdf.text(state.brief.caseInformation.caseName || state.brief.title, margin, y); y += 9; pdf.setFont("times", "normal"); pdf.setFontSize(10); pdf.text([state.brief.caseInformation.court, state.brief.caseInformation.citation, state.brief.caseInformation.date].filter(Boolean).join(" · "), margin, y); y += 17; briefParagraphs().forEach(({ title, text }) => { pdf.setFont("times", "bold"); pdf.setFontSize(12); if (y > 270) { pdf.addPage(); y = 22; } pdf.text(title, margin, y); y += 7; pdf.setFont("times", "normal"); pdf.setFontSize(10.5); pdf.splitTextToSize(text, 170).forEach(line => { if (y > 280) { pdf.addPage(); y = 22; } pdf.text(line, margin, y); y += 5; }); y += 7; }); pdf.save(`${safeFilename()}.pdf`); await createRevision("export"); notify("PDF exported"); }
async function exportDocx() { if (!window.docx) throw new Error("DOCX library is unavailable. Check your connection and reload."); const { Document, Packer, Paragraph, TextRun, HeadingLevel } = window.docx; const children = [new Paragraph({ text: state.brief.caseInformation.caseName || state.brief.title, heading: HeadingLevel.TITLE }), new Paragraph({ text: [state.brief.caseInformation.court, state.brief.caseInformation.citation, state.brief.caseInformation.date].filter(Boolean).join(" · ") })]; briefParagraphs().forEach(({ title, text }) => children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_1 }), ...text.split(/\n+/).map(line => new Paragraph({ children: [new TextRun(line)] })))); const doc = new Document({ creator: "Legal Brief Builder", keywords: "legal-brief-builder", title: state.brief.title, description: `LBB_Generated=true; LBB_Document_ID=${state.brief.provenance.documentId}; LBB_Application_Version=${APP_VERSION}; LBB_Template_Version=${TEMPLATE_VERSION}`, sections: [{ children }] }); download(await Packer.toBlob(doc), `${safeFilename()}.docx`); await createRevision("export"); notify("DOCX exported"); }
function safeFilename() { return (state.brief.caseInformation.caseName || state.brief.title || "brief").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "") || "brief"; }
async function importDraft(file) { try { const payload = JSON.parse(await file.text()); if (payload.format !== "legal-brief-builder" || payload.formatVersion !== DRAFT_FORMAT_VERSION || !payload.brief || !payload.brief.caseInformation || !payload.brief.sections) throw new Error("This file is not a compatible Legal Brief Builder draft."); const imported = structuredClone(payload.brief); imported.provenance = { ...payload.provenance, ...imported.provenance, documentId: imported.provenance?.documentId || imported.id, generatedBy: "Legal Brief Builder", revisions: imported.provenance?.revisions || [] }; await loadBrief(imported); await createRevision("import"); await saveDraft(imported); notify("Draft imported"); } catch (error) { notify(error.message || "The draft could not be imported.", true); } }
function renderDetails() { const details = $("#document-details"); details.replaceChildren(); const values = [["Document ID", state.brief.provenance.documentId], ["Created", formatDate(state.brief.provenance.createdAt)], ["Last modified", formatDate(state.brief.provenance.lastModifiedAt)], ["Revisions", state.brief.provenance.revisions.length], ["Application", APP_VERSION], ["Template", TEMPLATE_VERSION]]; values.forEach(([label, value]) => { const wrapper = document.createElement("div"); wrapper.className = "detail"; const term = document.createElement("dt"); term.textContent = label; const definition = document.createElement("dd"); definition.textContent = value; wrapper.append(term, definition); details.append(wrapper); }); }
function bindEvents() { $("#brief-title").addEventListener("input", event => { state.brief.title = event.target.value; handleEdit(); }); document.addEventListener("click", event => { const action = event.target.closest("[data-action]")?.dataset.action; if (!action) return; if (action === "new-brief") newBrief(); if (action === "open-drafts") showDrafts(); if (action === "open-settings") { renderDetails(); $("#settings-dialog").showModal(); } if (action === "close-modal") event.target.closest("dialog").close(); if (action === "import") $("#import-file").click(); if (action === "export-draft") exportDraft(); if (action === "previous-example") rotateExample(-1); if (action === "next-example") rotateExample(1); if (action === "export-pdf") exportPdf().catch(error => notify(error.message, true)); if (action === "export-docx") exportDocx().catch(error => notify(error.message, true)); }); $("#import-file").addEventListener("change", event => { if (event.target.files[0]) importDraft(event.target.files[0]); event.target.value = ""; }); }
async function init() { renderNavigation(); bindEvents(); try { const drafts = await getDrafts(); await loadBrief(drafts.sort((a, b) => new Date(b.modifiedAt) - new Date(a.modifiedAt))[0] || emptyBrief()); if (!drafts.length) await saveDraft(state.brief); } catch { state.brief = emptyBrief(); renderEditor(); updateHeader(); setStatus("Local storage unavailable", true); notify("IndexedDB is unavailable. Export backups to avoid losing work.", true); } }
init();
