export const APP_VERSION = "1.0.0";
export const TEMPLATE_VERSION = "1.0";
export const DRAFT_FORMAT_VERSION = 1;

export const sections = [
  { id: "case-information", title: "Case Name, Court, Citation, Date", type: "metadata", purpose: "Identify the case and provide its basic citation information.", instructions: ["Capture the identifying details before you begin your analysis.", "Use the citation format that your course, court, or jurisdiction expects."], fields: [{ id: "caseName", label: "Case name", placeholder: "International Shoe Co. v. Washington", example: "International Shoe Co. v. Washington" }, { id: "court", label: "Court", placeholder: "Supreme Court of the United States", example: "Supreme Court of the United States" }, { id: "citation", label: "Citation", placeholder: "326 U.S. 310", example: "326 U.S. 310 (1945)" }, { id: "date", label: "Date", placeholder: "1945", example: "1945 or January 12, 2024" }], examples: [{ title: "Example: International Shoe", source: "International Shoe Co. v. Washington", text: "Case name: International Shoe Co. v. Washington\nCourt: Supreme Court of the United States\nCitation: 326 U.S. 310 (1945)\nDate: May 14, 1945" }, { title: "Example: Brown v. Board of Education", source: "Brown v. Board of Education", text: "Case name: Brown v. Board of Education\nCourt: Supreme Court of the United States\nCitation: 347 U.S. 483 (1954)\nDate: May 17, 1954" }, { title: "Example: Marbury v. Madison", source: "Marbury v. Madison", text: "Case name: Marbury v. Madison\nCourt: Supreme Court of the United States\nCitation: 5 U.S. (1 Cranch) 137 (1803)\nDate: February 24, 1803" }] },
  { id: "facts", title: "Facts", type: "textarea", purpose: "Record the legally significant facts necessary to understand the dispute and decision.", instructions: ["Focus on facts that affect the legal analysis, not every detail in the record.", "Identify the parties, their actions, and the event that created the dispute."], examples: [{ title: "Example: International Shoe", source: "International Shoe Co. v. Washington", text: "International Shoe, a Delaware corporation, employed salespeople in Washington but had no office or store there. Washington sought unpaid unemployment compensation contributions from the company." }, { title: "Example: Erie Railroad", source: "Erie Railroad Co. v. Tompkins", text: "Tompkins was struck by an Erie Railroad train while walking along the tracks in Pennsylvania. He sued Erie in federal court in New York under diversity jurisdiction." }] },
  { id: "procedural-history", title: "Procedural History", type: "textarea", purpose: "Explain how the case reached the present court, including relevant lower-court proceedings.", instructions: ["Trace only the procedural steps that help explain the question before the court.", "Note the result at each important stage and who appealed."], examples: [{ title: "Example: Procedural path", source: "Original example", text: "The trial court entered judgment for the defendant. The intermediate appellate court reversed. The Supreme Court granted review to resolve the legal issue." }] },
  { id: "issues", title: "Issue(s)", type: "textarea", purpose: "State the legal question or questions the court was required to resolve.", instructions: ["Phrase each issue as a focused legal question.", "Include the relevant facts and legal standard when they narrow the question."], examples: [{ title: "Example: Personal jurisdiction", source: "International Shoe Co. v. Washington", text: "Does a state court have personal jurisdiction over an out-of-state corporation whose in-state activities establish sufficient contacts with the state?" }] },
  { id: "applicable-rules", title: "Applicable Rule(s) of Law", type: "textarea", purpose: "Identify the governing legal rule or standard applied by the court.", instructions: ["State the rule in your own words, then include a key formulation from the opinion if useful.", "Separate the general rule from any test or factors the court applies."], examples: [{ title: "Example: Rule", source: "International Shoe Co. v. Washington", text: "Due process permits personal jurisdiction when a defendant has minimum contacts with the forum such that maintaining the suit does not offend traditional notions of fair play and substantial justice." }] },
  { id: "holdings", title: "Holding(s)", type: "textarea", purpose: "State the court's answer to the legal issue.", instructions: ["Answer the issue directly and precisely.", "Distinguish the holding from the broader reasoning or dicta."], examples: [{ title: "Example: Holding", source: "Original example", text: "Yes. The corporation's activities in Washington were sufficiently related to the claim and substantial enough to support jurisdiction consistent with due process." }] },
  { id: "court-order", title: "The Court's Order", type: "textarea", purpose: "State what the court actually did with the case, such as affirming, reversing, remanding, dismissing, granting, or denying relief.", instructions: ["Use the court's operative disposition.", "Be clear about what happens next to the parties or lower-court judgment."], examples: [{ title: "Example: Disposition", source: "Original example", text: "The Court affirmed the judgment below and remanded the matter for further proceedings consistent with its opinion." }] },
  { id: "reasoning", title: "Reasoning", type: "textarea", purpose: "Explain why the court reached its holding.", instructions: ["Connect the rule to the important facts in a logical sequence.", "Mention competing arguments and explain why the court accepted or rejected them."], examples: [{ title: "Example: Analysis", source: "Original example", text: "The Court connected the company's deliberate business activity in the state to the dispute. Because the claim arose from those contacts, requiring the company to defend there was foreseeable and fair." }] },
  { id: "new-information", title: "New Information", type: "textarea", purpose: "Record new legal concepts, terminology, doctrines, procedural concepts, or other information learned from the case.", instructions: ["Capture ideas you want to revisit, not just a second summary of the opinion.", "Define unfamiliar terms in language you will recognize later."], examples: [{ title: "Example: Study note", source: "Original example", text: "Minimum contacts: the relationship between a defendant, the forum, and the litigation that makes jurisdiction constitutionally reasonable." }] },
  { id: "questions-comments-speculations", title: "Questions, Comments, and Speculations", type: "textarea", purpose: "Record questions, observations, possible implications, disagreements, and areas requiring further research.", instructions: ["Leave yourself useful questions for class discussion or later research.", "Speculation is welcome here; label it clearly so it stays distinct from the holding."], examples: [{ title: "Example: Open question", source: "Original example", text: "How would the result change if the company's sales in the state were unrelated to the claim? What amount of activity should count as purposeful availment?" }] }
];

export function emptyBrief() {
  const now = new Date().toISOString();
  const id = `LBB-${crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`}`;
  return { id, title: "Untitled brief", createdAt: now, modifiedAt: now, caseInformation: { caseName: "", court: "", citation: "", date: "" }, sections: Object.fromEntries(sections.filter(section => section.type !== "metadata").map(section => [section.id, ""])), provenance: { documentId: id, createdAt: now, lastModifiedAt: now, applicationVersion: APP_VERSION, templateVersion: TEMPLATE_VERSION, formatVersion: DRAFT_FORMAT_VERSION, generatedBy: "Legal Brief Builder", revisions: [] } };
}
